Get rid of all the shell globbing in the incremental backup script

diff --git a/templates/default/upload-incrementals.erb b/templates/default/upload-incrementals.erb
--- a/templates/default/upload-incrementals.erb
+++ b/templates/default/upload-incrementals.erb
@@ -13,6 +13,16 @@ data_dirs="<%= node['et_cassandra']['config']['data_file_directories'].join(' ')
 work_dir="${root_dir}/backup_work_dir"
 old_pwd="$PWD"
 
+work_dir_fs_id=`/usr/bin/stat -f -c %i ${work_dir}`
+
+# Ensure that $work_dir and $data_dirs are on the same filesystem
+for data_dir in $data_dirs; do
+  if [[ $(stat -f -c %i ${data_dir}) != ${work_dir_fs_id} ]]; then
+    echo "ERROR: Backup work_dir ${work_dir} is not on the same filesystem with data_dir (${data_dir})"
+    exit 99
+  fi
+done
+
 mkdir -p "${work_dir}"
 
 backup_date=`date +%Y-%m-%dT%H%M%S`
@@ -27,44 +37,52 @@ function contained_by {
 let dir_index=1
 
 for data_dir in $data_dirs; do
+  backup_holding_dir="${work_dir}/${backup_date}/${dir_index}"
+
   for keyspace in `find $data_dir -maxdepth 1 -mindepth 1 -type d -exec basename {} \;`; do
     if contained_by "${keyspace}" "${SKIP_KEYSPACES[@]}"; then continue; fi
 
+    for table in `find ${data_dir}/${keyspace} -maxdepth 1 -mindepth 1 -type d -exec basename {} \;`; do
+      mkdir -p "${backup_holding_dir}/${keyspace}/${table}"
+      if [ -d "${data_dir}/${keyspace}/${table}/backups" ]; then
+        mv "${data_dir}/${keyspace}/${table}/backups" "${backup_holding_dir}/${keyspace}/${table}/"
+      fi
+    done
+
     tarball="${work_dir}/$keyspace-$dir_index.tar.gz"
 
-    if [ -n "$(find $data_dir/$keyspace -maxdepth 2 -mindepth 2 -name backups -type d | head -n 1)" ] && \
-       ls -A $data_dir/$keyspace/*/backups/* > /dev/null 2>&1; then
-      cd "$data_dir"
+    cd "${backup_holding_dir}"
 
-      if [ -e "$tarball" ]; then
-        echo "$tarball already exists! Bailing instead of overwriting it."
-        exit 1
-      fi
-
-      # It's important to remove files in the backups directory as atomically
-      # as possible because this directory is going to be updated as we read it
-      tar --remove-files -czf "$tarball" "$keyspace"/*/backups/*
-
-      trap "cd \"$old_pwd\"; exit" INT TERM EXIT
-
-      /usr/local/bin/s3cmd put \
-        --quiet \
-        --access_key $AWS_ACCESS_KEY_ID \
-        --secret_key $AWS_SECRET_ACCESS_KEY \
-        --server-side-encryption \
-        --region $REGION \
-        "$tarball" \
-        "s3://$BUCKET/cassandra/<%= node.chef_environment %>/<%= node['fqdn'] %>/incrementals/$backup_date/$keyspace-$dir_index.tar.gz"
-
-      rm -f "$tarball"
-
-      trap - INT TERM EXIT
-    else
-      echo "Nothing to back up in $data_dir/$keyspace/*/backups"
+    if [ -e "$tarball" ]; then
+      echo "$tarball already exists! Bailing instead of overwriting it."
+      exit 1
     fi
-  done
+
+    # It's important to remove files in the backups directory as atomically
+    # as possible because this directory is going to be updated as we read it
+    tar --remove-files -czf "$tarball" "${keyspace}"
+
+    trap "cd \"$old_pwd\"; exit" INT TERM EXIT
+
+    /usr/local/bin/s3cmd put \
+      --quiet \
+      --access_key $AWS_ACCESS_KEY_ID \
+      --secret_key $AWS_SECRET_ACCESS_KEY \
+      --server-side-encryption \
+      --region $REGION \
+      "$tarball" \
+      "s3://$BUCKET/cassandra/<%= node.chef_environment %>/<%= node['fqdn'] %>/incrementals/$backup_date/$keyspace-$dir_index.tar.gz"
+
+    rm -f "$tarball"
+    rm -rf "${backup_holding_dir}/${keyspace}"
+
+    trap - INT TERM EXIT
+  done # keyspaces loop
+  rmdir "${backup_holding_dir}"
   let dir_index++
 done
+
+rmdir "${work_dir}/${backup_date}"
 
 cd "$old_pwd"
 
